### ISSUE TITLE
Not installing (macOS Big Sur)

### ISSUE THREAD

**Issue by braydentraas** [fboender/multi-git-status#44]
Both the global option:
```
install mgitstatus -m 755 /usr/local/bin/
install: -m: No such file or directory

```

And suggested current user option:
```
install mgitstatus -m 755 /Users/brayden/.local/bin/
install: -m: No such file or directory
```

fail on macOS big sur. Shouldn't `install` have all options before the source?
https://man.openbsd.org/install.1 

Swapping the order in `Makefile` seems to work 
`install -m 755 mgitstatus /Users/brayden/.local/bin/`

**Comment by SuperSandro2000** [comment]
MacOS has by default terribly old coreutils and bash. If you have a recent version from homebrew this will just work fine.

**Comment by tabulon** [comment]
Hi @SuperSandro2000,

While your comments about macOS shipping ridicolously outdated software is generally true, it need not be an issue here.

-- unless there is any particular reason for not following the [official GNU documentation](https://www.man7.org/linux/man-pages/man1/install.1.html) for the install command?

The fix suggested by @braydentraas for the `Makefile` is doing nothing but following the documented way of invoking the `install` command :

```shell
install -m 755 mgitstatus $(DESTDIR)$(PREFIX)/bin/
```

The above should work across the board on any Unix-like system (Linux, BSD, macOS, ...), as opposed to the way it's currently beeing done in the `Makefile` (which fails under macOS and who knows where else):

```shell
install mgitstatus -m 755 $(DESTDIR)$(PREFIX)/bin/
```

That may happen to work on some versions of `install`, but only as an unintended (or at least, undocumented) "feature", probably as a side effect of some library being used under the hood for parsing command line options.

Otherwise, the [official man pages](https://www.man7.org/linux/man-pages/man1/install.1.html) for GNU 'install'  (on Linux, by the way) is quite clear:

```man
NAME
       install - copy files and set attributes
SYNOPSIS 
       install [OPTION]... [-T] SOURCE DEST
       install [OPTION]... SOURCE... DIRECTORY
       install [OPTION]... -t DIRECTORY SOURCE...
       install [OPTION]... -d DIRECTORY...
```

**Comment by tabulon** [comment]
With regards to @SuperSandro2000's suggestion about `hombrew` and `GNU coreutils`:

I am a long time user of both, like many others on macOS; but there are a few **CAVEATS**and pitfalls to be aware of:

Under macOS, you shouldn't really install the commands packaged in `GNU coreutils` under their standard names (ls, find, install, ...) in any directory that's susceptible to be added to your PATH. 

If you go with standard names, bad things do happen sooner or later... because some scripts (system or 3rd party) assume BSD or macOS versions of those commands (with conflicting switches).... 

Therefore, many people (including myself) opt for alternate names for GNU commands,  as wisely encouraged by `homebrew` (gls, gfind, ginstall, ...).

That means, when you encounter something like this issue, you still have to remember doing :

```shell
PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH" PREFIX=~/.local make install 
```

Here's a bash function that saves you some typing for invoking scripts that assume GNU commands :

```bash
gnuphil() {
   local cmd="$1";  shift;
   if [ -z "$cmd" ]  ; then
       1>&2 echo "gnuphil: Nothing to do. Give me a command line run (during which GNU versions of any standard command will prevail)... "; 
       1>&2 echo "USAGE: gnuphil cmd [options] arguments"; 
       return  2
   fi
   PATH="$(brew --prefix coreutils)/libexec/gnubin:$PATH"  $cmd "$@"
}
```

For this particular issue, assuming you want to install `mgitstatus` under `~/.local`, as in the example,  you can use the above function as follows :

```
cd multi-git-status
PREFIX=~/.local gnuphil make install
```

You obviously need `hombrew` and `GNU coreutils` already installed on your system for this to work.

**Comment by fboender** [comment]
> fail on macOS big sur. Shouldn't install have all options before the source?

Yeah, the `-m` option should come first. I've fixed this in commit https://github.com/fboender/multi-git-status/commit/1fbd99e476f0f55dc05ecb848455a403ba56f0a1.
